### PR TITLE
Added the web app code

### PR DESCRIPTION
**Pull request by kpulkit29**
Refer README for instruction and web app workflow

### CODE REVIEW

**Review by peter-evans — CHANGES_REQUESTED** [review]
Thanks for the PR!
Please could you remove the `node_modules` directory and add it to a `.gitignore` file. After that change I'll be able to review it easier. Thanks.

**Comment by kpulkit29** [comment]
I have added node_modules to gitignore

**Comment by peter-evans** [comment]
@kpulkit29 Please include source files for the solidity code in the PR.

I took a look at the code [here](https://rinkeby.etherscan.io/address/0x55e9d99646a3fd56375fca795fd2db5510a990e1#code). It looks like it won't be secure for the reason that @felixwatts outlined in [this comment](https://github.com/AvocadoNetwork/governance/issues/6#issuecomment-408014683).
@felixwatts, it would be a great help if you could explain a bit further about how your proposed solution solves the problem. I'm having trouble understanding how making the first transaction makes it secure. Can't the miner/validator do the same?

**Comment by kpulkit29** [comment]
So the sender first needs to transfer his tokens to the contract address
using avocado transfer function .Then when the receiver clicks accept the
tokens are transferred from contract address to recipient .In my smart
contract there is a receive function which has some checks.Here the  smart
contract calls the avocado token transfer function and then transfers the
token as well the fees to recipient address

**Comment by kpulkit29** [comment]
Moreover the code is published on rinkeby

**Comment by kpulkit29** [comment]
I am using your avocado token contract simultaneously.There is always scope
for improvement but I guess my proposed solution is a good working example

**Comment by kpulkit29** [comment]
Sir the first transfer is necessary as when my contracts calls Avocado transfer function The contract becomes the msg.sender (I guess this explains everything)

**Comment by peter-evans** [comment]
@kpulkit29 I've just noticed [this comment](https://github.com/AvocadoNetwork/governance/issues/6#issuecomment-419631367) from @sameer2800 which explains it well. This is how it should work to be secure.

- When calling the `sendTo` function, instead of sending the email address to the contract the web application should send the hash.
- The hash is sent to the recipient in the email (maybe as a URL parameter of the link to click and receive the AVO)
- There should be a two stage process to receive the AVO.
   1. The recipient makes a transaction to the contract (sending only the hash) to indicate that they want to receive the tokens. The contract locks the tokens to the recipients Ethereum address for a set period, say 10 minutes.
   2. The recipient then makes another transaction sending their email address. This is compared to the hash and the tokens are released to the address stored in step 1.

**Comment by kpulkit29** [comment]
Sir there was nothing mentioned about token locking according to
time.moreover I am generating the hash in the contract.Its one and the same
thing.

**Comment by kpulkit29** [comment]
Step 2 is already being implemented.Kindly review

**Review by peter-evans — APPROVED** [review]

**Comment by kpulkit29** [comment]
Thanks a lot.Nice to work on such interesting project.

**Comment by peter-evans** [comment]
> Sir there was nothing mentioned about token locking according to time.moreover I am generating the hash in the contract.Its one and the same thing.

You are right. There was nothing mentioned in the original task, but if you had read the comments you would have seen the discussion about designing a secure implementation. This implementation is not secure because the email addresses will be accessible on the network and people could potentially steal tokens.

I'm going to pay this bounty out anyway because perhaps the task wasn't clear. We'll figure out how to improve this solution later. Thank you for your effort.

**Pull request merged**
